"""analyze_logs.py — metrics + plots from logs/*.csv (offline).

Covers the §13 metrics that come from logs:
    * kinematics_test.csv -> commanded vs measured table
                             (+ docs/evidence/kinematics_validation.md)
    * odometry.csv        -> drift table + overlay plot
    * run.csv             -> following metrics (cross-track, state timeline)
Writes docs/evidence/metrics.md and docs/evidence/odometry_vs_gps.png.

Run:  python tools/analyze_logs.py
"""

import csv
import math
import os
import sys

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
sys.path.insert(0, os.path.join(ROOT, "controllers", "intellibot_controller"))
import config  # noqa: E402

LOGS = os.path.join(ROOT, "logs")
EV = os.path.join(ROOT, "docs", "evidence")


def load(name):
    path = os.path.join(LOGS, name)
    if not os.path.exists(path):
        return None
    with open(path) as f:
        return list(csv.DictReader(f))


def _wrap_deg(a):
    return math.degrees(math.atan2(math.sin(a), math.cos(a)))


def kinematics_section(lines):
    rows = load("kinematics_test.csv")
    if not rows:
        lines.append("## Kinematics validation\n\nnot yet measured "
                     "(run drive_test with DRIVE_TEST_MODE=kinematics)\n")
        return
    table = ["| v_cmd (m/s) | w_cmd (rad/s) | wL, wR cmd (rad/s) | v_meas (m/s) "
             "| w_meas (rad/s) | v err % | w err % |",
             "|---|---|---|---|---|---|---|"]
    for r in rows:
        vc, wc = float(r["v_cmd"]), float(r["w_cmd"])
        vm, wm = float(r["v_meas"]), float(r["w_meas"])
        ve = f"{100 * (vm - vc) / abs(vc):+.2f}" if abs(vc) > 1e-9 else "n/a"
        we = f"{100 * (wm - wc) / abs(wc):+.2f}" if abs(wc) > 1e-9 else "n/a"
        table.append(f"| {vc:+.2f} | {wc:+.2f} | {float(r['wl_cmd']):+.2f}, "
                     f"{float(r['wr_cmd']):+.2f} | {vm:+.4f} | {wm:+.4f} | "
                     f"{ve} | {we} |")
    lines.append("## Kinematics: commanded vs measured\n")
    lines.extend(table)
    lines.append("")
    # dedicated Phase 3.3 evidence file
    with open(os.path.join(EV, "kinematics_validation.md"), "w") as f:
        f.write("# Kinematics validation (Phase 3.3)\n\n"
                "Generated by `tools/analyze_logs.py` from `logs/kinematics_test.csv`\n"
                "(`DRIVE_TEST_MODE=kinematics`, world `warehouse_drive_test.wbt`).\n\n"
                "Method: (v, w) -> `inverse_kinematics` -> wheel speeds; after 1 s\n"
                "settling, v and w are measured for 4 s from per-step GPS/IMU\n"
                "differences (v = displacement projected on heading / dt,\n"
                "w = wrapped yaw change / dt).\n\n")
        f.write("\n".join(table) + "\n")


def odometry_section(lines):
    rows = load("odometry.csv")
    if not rows:
        lines.append("## Odometry vs GPS\n\nnot yet measured "
                     "(run drive_test with DRIVE_TEST_MODE=odometry)\n")
        return
    lines.append("## Odometry vs GPS+IMU (drift)\n")
    lines.append("| trajectory | distance driven (m) | final pos err (cm) "
                 "| max pos err (cm) | final heading err (deg) |")
    lines.append("|---|---|---|---|---|")
    by_traj = {}
    for r in rows:
        by_traj.setdefault(r["traj"], []).append(r)
    fig, axes = plt.subplots(1, len(by_traj), figsize=(5 * len(by_traj), 4.8))
    axes = axes if len(by_traj) > 1 else [axes]
    for ax, (traj, rs) in zip(axes, by_traj.items()):
        gx = [float(r["x_gps"]) for r in rs]
        gy = [float(r["y_gps"]) for r in rs]
        ox = [float(r["x_odom"]) for r in rs]
        oy = [float(r["y_odom"]) for r in rs]
        ax.plot(gx, gy, "-", color="#1d4ed8", lw=2.5, label="GPS+IMU (truth)")
        ax.plot(ox, oy, "--", color="#ea580c", lw=1.8, label="wheel odometry")
        ax.plot(gx[0], gy[0], "o", color="black", ms=5, label="start")
        dist = sum(math.hypot(gx[i + 1] - gx[i], gy[i + 1] - gy[i])
                   for i in range(len(gx) - 1))
        errs = [math.hypot(a - c, b - d) for a, b, c, d in zip(gx, gy, ox, oy)]
        last = rs[-1]
        herr = abs(_wrap_deg(float(last["th_gps"]) - float(last["th_odom"])))
        lines.append(f"| {traj} | {dist:.2f} | {errs[-1] * 100:.2f} | "
                     f"{max(errs) * 100:.2f} | {herr:.2f} |")
        ax.set_title(f"{traj}: final error {errs[-1] * 100:.1f} cm, {herr:.1f} deg")
        ax.set_aspect("equal", adjustable="datalim")
        ax.grid(alpha=0.3)
        ax.set_xlabel("x (m)")
        ax.set_ylabel("y (m)")
        ax.legend(fontsize=8)
    fig.suptitle("Wheel odometry vs GPS+IMU ground truth (Webots)")
    fig.tight_layout()
    fig.savefig(os.path.join(EV, "odometry_vs_gps.png"), dpi=150)
    lines.append("\n![odometry vs gps](odometry_vs_gps.png)\n")


def run_section(lines):
    rows = load("run.csv")
    if not rows:
        lines.append("## Mission run (run.csv)\n\nnot yet measured "
                     "(run the intellibot_controller demo in Webots)\n")
        return
    cte = [float(r["cross_track_err"]) for r in rows if r["cross_track_err"]]
    states = [r["state"] for r in rows]
    lines.append("## Mission run\n")
    lines.append(f"- rows logged: {len(rows)}")
    if cte:
        lines.append(f"- mean cross-track error: {sum(cte)/len(cte):.3f} m")
        lines.append(f"- max cross-track error: {max(cte):.3f} m")
    seen = []
    for s in states:
        if not seen or seen[-1] != s:
            seen.append(s)
    lines.append(f"- state sequence: {' -> '.join(seen)}")
    lines.append("")
    # 6.3 overlay evidence: A* reference vs actual trajectory
    try:
        from plot_run import plot_run
        plot_run(os.path.join(LOGS, "run.csv"))
        lines.append("![planned vs actual](planned_vs_actual.png)\n")
    except Exception as exc:
        lines.append(f"(planned_vs_actual plot failed: {exc})\n")


def campaign_section(lines):
    """Repeatability campaign (checklist 6.8): logs/run_<i>.csv -> summary."""
    paths = []
    for name in os.listdir(LOGS):
        stem, ext = os.path.splitext(name)
        if ext == ".csv" and stem.startswith("run_") and stem[4:].isdigit():
            paths.append((int(stem[4:]), os.path.join(LOGS, name)))
    paths.sort()
    if not paths:
        return
    table = ["| run | result | time (s) | final goal err (m) |", "|---|---|---|---|"]
    ok = 0
    for idx, p in paths:
        rows = list(csv.DictReader(open(p)))
        if not rows:
            continue
        last = rows[-1]
        result = last["state"]
        ok += result == "DONE"
        dur = float(last["t"]) - float(rows[0]["t"])
        goal = math.hypot(float(last["x"]) - config.ZONE_B_CENTER[0],
                          float(last["y"]) - config.ZONE_B_CENTER[1])
        table.append(f"| {idx} | {result} | {dur:.1f} | {goal:.2f} |")
    block = (f"**Success rate: {ok}/{len(paths)}**", "")
    lines.append("## Repeatability campaign (different start poses)\n")
    lines.extend(table + block)
    with open(os.path.join(EV, "runs_summary.md"), "w") as f:
        f.write("# Repeatability campaign (checklist 6.8)\n\n"
                "Runs from different start poses: set `RUN_INDEX=<i>` before\n"
                "starting Webots (the supervisor teleports the robot to\n"
                "`config.CAMPAIGN_STARTS[i]`; the log goes to `logs/run_<i>.csv`).\n\n")
        f.write("\n".join(table + block) + "\n")
    print(f"wrote {os.path.join(EV, 'runs_summary.md')}")


def main():
    os.makedirs(EV, exist_ok=True)
    lines = ["# Metrics summary (generated by tools/analyze_logs.py)\n"]
    kinematics_section(lines)
    odometry_section(lines)
    run_section(lines)
    campaign_section(lines)
    lines.append("Not covered here (measured by dedicated tools): LiDAR range "
                 "accuracy (`plot_lidar.py`), detector rates "
                 "(`eval_detector.py`), A* optimality (`plot_astar.py`).\n")
    out = os.path.join(EV, "metrics.md")
    with open(out, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
