"""analyze_logs.py — metrics + plots from logs/*.csv (offline).

Covers the §13 metrics that come from logs:
    * kinematics_test.csv -> commanded vs measured table
    * odometry.csv        -> final drift + overlay plot
    * run.csv             -> following metrics (cross-track, state timeline)
Writes docs/evidence/metrics.md and docs/evidence/odometry_vs_gps.png.

Run:  python tools/analyze_logs.py
"""

import csv
import math
import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
LOGS = os.path.join(ROOT, "logs")
EV = os.path.join(ROOT, "docs", "evidence")


def load(name):
    path = os.path.join(LOGS, name)
    if not os.path.exists(path):
        return None
    with open(path) as f:
        return list(csv.DictReader(f))


def kinematics_section(lines):
    rows = load("kinematics_test.csv")
    if not rows:
        lines.append("## Kinematics validation\n\nnot yet measured "
                     "(run drive_test with DRIVE_TEST_MODE=kinematics)\n")
        return
    lines.append("## Kinematics: commanded vs measured\n")
    lines.append("| v_cmd | w_cmd | v_meas | w_meas | v_err % | w_err % |")
    lines.append("|---|---|---|---|---|---|")
    for r in rows:
        vc, wc = float(r["v_cmd"]), float(r["w_cmd"])
        vm, wm = float(r["v_meas"]), float(r["w_meas"])
        ve = 100 * abs(vm - vc) / abs(vc) if abs(vc) > 1e-9 else float("nan")
        we = 100 * abs(wm - wc) / abs(wc) if abs(wc) > 1e-9 else float("nan")
        lines.append(f"| {vc} | {wc} | {vm:.3f} | {wm:.3f} | "
                     f"{ve:.1f} | {we:.1f} |")
    lines.append("")


def odometry_section(lines):
    rows = load("odometry.csv")
    if not rows:
        lines.append("## Odometry vs GPS\n\nnot yet measured "
                     "(run drive_test with DRIVE_TEST_MODE=odometry)\n")
        return
    fig, ax = plt.subplots(figsize=(9, 7))
    lines.append("## Odometry vs GPS+IMU (drift)\n")
    lines.append("| trajectory | final pos err (m) | final heading err (deg) |")
    lines.append("|---|---|---|")
    by_traj = {}
    for r in rows:
        by_traj.setdefault(r["traj"], []).append(r)
    for traj, rs in by_traj.items():
        gx = [float(r["x_gps"]) for r in rs]
        gy = [float(r["y_gps"]) for r in rs]
        ox = [float(r["x_odom"]) for r in rs]
        oy = [float(r["y_odom"]) for r in rs]
        ax.plot(gx, gy, "-", label=f"{traj} GPS", lw=2)
        ax.plot(ox, oy, "--", label=f"{traj} odom", lw=1.5)
        last, lasto = rs[-1], rs[-1]
        perr = math.hypot(float(last["x_gps"]) - float(lasto["x_odom"]),
                          float(last["y_gps"]) - float(lasto["y_odom"]))
        herr = math.degrees(abs(float(last["th_gps"]) - float(lasto["th_odom"])))
        lines.append(f"| {traj} | {perr:.3f} | {herr:.1f} |")
    ax.set_aspect("equal")
    ax.grid(alpha=0.3)
    ax.legend(fontsize=8)
    ax.set_title("Odometry vs GPS+IMU ground truth")
    os.makedirs(EV, exist_ok=True)
    fig.savefig(os.path.join(EV, "odometry_vs_gps.png"), dpi=150)
    lines.append("\n![odometry vs gps](odometry_vs_gps.png)\n")


def run_section(lines):
    rows = load("run.csv")
    if not rows:
        lines.append("## Mission run (run.csv)\n\nnot yet measured "
                     "(run the intellibot_controller demo in Webots)\n")
        return
    cte = [float(r["cross_track_err"]) for r in rows if r["cross_track_err"]]
    states = [r["state"] for r in rows]
    lines.append("## Mission run\n")
    lines.append(f"- rows logged: {len(rows)}")
    if cte:
        lines.append(f"- mean cross-track error: {sum(cte)/len(cte):.3f} m")
        lines.append(f"- max cross-track error: {max(cte):.3f} m")
    seen = []
    for s in states:
        if not seen or seen[-1] != s:
            seen.append(s)
    lines.append(f"- state sequence: {' -> '.join(seen)}")
    lines.append("")


def main():
    lines = ["# Metrics summary (generated by tools/analyze_logs.py)\n"]
    kinematics_section(lines)
    odometry_section(lines)
    run_section(lines)
    lines.append("Not covered here (measured by dedicated tools): LiDAR range "
                 "accuracy (`plot_lidar.py`), detector rates "
                 "(`eval_detector.py`), A* optimality (`plot_astar.py`).\n")
    os.makedirs(EV, exist_ok=True)
    out = os.path.join(EV, "metrics.md")
    with open(out, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
