"""check_evidence.py — Phase 7.2 evidence folder check (offline).

Verifies which mid-eval evidence artifacts exist (and are non-trivial in
size), prints a table, and writes docs/evidence/inventory.md. Exit code 0
only when every P0 artifact exists.

Run:  python tools/check_evidence.py
"""

import os
import sys

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
EV = os.path.join(ROOT, "docs", "evidence")

# (path relative to repo, priority, description)
EXPECTED = [
    ("docs/evidence/world_topdown.png", "P0", "world screenshot (top-down)"),
    ("docs/evidence/world_angle.png", "P0", "world screenshot (angled)"),
    ("docs/evidence/kinematics_validation.md", "P0", "kinematics commanded-vs-measured table"),
    ("docs/evidence/odometry_vs_gps.png", "P0", "odometry vs GPS overlay plot"),
    ("docs/evidence/detector_eval.md", "P0", "detector evaluation table"),
    ("docs/evidence/detection_example.png", "P0", "annotated detection example"),
    ("docs/evidence/position_estimate.md", "P0", "package position-estimate error"),
    ("docs/evidence/astar_pickup_to_zoneB.png", "P0", "A* planning figure"),
    ("docs/evidence/planned_vs_actual.png", "P0", "planned vs actual overlay"),
    ("docs/evidence/lidar_scan.png", "P0", "LiDAR scan world-frame plot"),
    ("docs/evidence/metrics.md", "P0", "metrics summary"),
    ("docs/evidence/runs_summary.md", "P1", "repeatability campaign summary"),
    ("docs/evidence/run_full.mp4", "P0", "<=60 s screen recording of a full run"),
    ("logs/run.csv", "P0", "final console run log (CSV)"),
    ("README.md", "P0", "run instructions"),
    ("docs/qa_prep.md", "P1", "viva Q&A"),
    ("docs/demo_script.md", "P0", "demo script"),
    ("IntelliBot_MidTerm_Review.pptx", "P0", "review deck"),
]


def main():
    rows, missing_p0 = [], []
    for rel, pri, desc in EXPECTED:
        p = os.path.join(ROOT, rel)
        if os.path.exists(p) and os.path.getsize(p) > 100:
            rows.append(f"| {pri} | OK | `{rel}` | {desc} |")
        else:
            rows.append(f"| {pri} | MISSING | `{rel}` | {desc} |")
            if pri == "P0":
                missing_p0.append(rel)

    lines = ["# Evidence inventory (generated by tools/check_evidence.py)\n",
             "| pri | status | artifact | what |", "|---|---|---|---|"] + rows
    lines += ["", f"**P0 missing: {len(missing_p0)}**"
              + (": " + ", ".join(f"`{m}`" for m in missing_p0) if missing_p0 else " — none")]
    out = os.path.join(EV, "inventory.md")
    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("\n".join(lines[3:]))
    print(f"\nwrote {out}")
    sys.exit(1 if missing_p0 else 0)


if __name__ == "__main__":
    main()
